// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }

    [Fact]
    public void NHSTest()
    {
        driver.Navigate().GoToUrl("https://services.nhsbsa.nhs.uk/check-for-help-paying-nhs-costs/start");

        driver.FindElement(By.Id("next-button")).Click();
        driver.FindElement(By.Id("label-england")).Click();
        driver.FindElement(By.Id("next-button")).Click();
        driver.FindElement(By.Id("radio-no")).Click();
        driver.FindElement(By.Id("next-button")).Click();
    }
  [Fact]
  public void Test3() {
    driver.Navigate().GoToUrl("https://www.rightmove.co.uk/");
    driver.FindElement(By.Name("typeAheadInputField")).SendKeys("MK5 8DS");

    driver.FindElement(By.CssSelector(".residentialLetButton")).Click();
    {
      var dropdown = driver.FindElement(By.Id("radius"));
      dropdown.FindElement(By.XPath("//option[. = 'Within 1 mile']")).Click();
    }
    driver.FindElement(By.Id("radius")).Click();
    {
      var dropdown = driver.FindElement(By.Id("minPrice"));
      dropdown.FindElement(By.XPath("//option[. = '150 PCM']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("maxPrice"));
      dropdown.FindElement(By.XPath("//option[. = '400 PCM']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("minBedrooms"));
      dropdown.FindElement(By.XPath("//option[. = '1']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("maxBedrooms"));
      dropdown.FindElement(By.XPath("//option[. = '2']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("displayPropertyType"));
      dropdown.FindElement(By.XPath("//option[. = 'Houses']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("maxDaysSinceAdded"));
      dropdown.FindElement(By.XPath("//option[. = 'Last 3 days']")).Click();
    }
    driver.FindElement(By.Id("submit")).Click();
  }
}
